export interface QuizQuestion {
  id: number
  question: string
  options: string[]
  correctAnswer: number // index of correct option (0-3)
  category: "cybercrime" | "cyber-literacy" | "online-safety" | "digital-security"
}

export const quizQuestions: QuizQuestion[] = [
  // Cybercrime Questions
  {
    id: 1,
    question: "What is phishing?",
    options: [
      "A type of computer virus",
      "Fraudulent attempt to obtain sensitive information by disguising as trustworthy entity",
      "A method of data encryption",
      "A type of firewall",
    ],
    correctAnswer: 1,
    category: "cybercrime",
  },
  {
    id: 2,
    question: "Which of the following is NOT a type of malware?",
    options: ["Trojan Horse", "Ransomware", "Firewall", "Spyware"],
    correctAnswer: 2,
    category: "cybercrime",
  },
  {
    id: 3,
    question: "What does ransomware typically do?",
    options: [
      "Encrypts files and demands payment for decryption",
      "Monitors user activity",
      "Deletes system files",
      "Creates fake websites",
    ],
    correctAnswer: 0,
    category: "cybercrime",
  },
  {
    id: 4,
    question: "Which of these is a common social engineering attack?",
    options: ["DDoS attack", "SQL injection", "Pretexting", "Buffer overflow"],
    correctAnswer: 2,
    category: "cybercrime",
  },
  {
    id: 5,
    question: "What is identity theft?",
    options: [
      "Stealing physical documents",
      "Hacking into databases",
      "Using someone's personal information without permission for fraudulent purposes",
      "Creating fake social media profiles",
    ],
    correctAnswer: 2,
    category: "cybercrime",
  },
  {
    id: 6,
    question: "Which attack involves overwhelming a server with traffic?",
    options: ["Phishing", "DDoS (Distributed Denial of Service)", "Man-in-the-middle", "Cross-site scripting"],
    correctAnswer: 1,
    category: "cybercrime",
  },
  {
    id: 7,
    question: "What is a botnet?",
    options: [
      "A type of antivirus software",
      "A secure network protocol",
      "A network of infected computers controlled remotely",
      "A password manager",
    ],
    correctAnswer: 2,
    category: "cybercrime",
  },
  {
    id: 8,
    question: "Which of these is characteristic of a strong password?",
    options: [
      "Contains only letters",
      "Is easy to remember",
      "Contains a mix of uppercase, lowercase, numbers, and symbols",
      "Is the same across all accounts",
    ],
    correctAnswer: 2,
    category: "cybercrime",
  },
  {
    id: 9,
    question: "What is spyware designed to do?",
    options: [
      "Encrypt files",
      "Monitor and collect user information without consent",
      "Block internet access",
      "Speed up computer performance",
    ],
    correctAnswer: 1,
    category: "cybercrime",
  },
  {
    id: 10,
    question: "Which method is commonly used to distribute malware?",
    options: ["Email attachments", "Software updates", "Antivirus scans", "System backups"],
    correctAnswer: 0,
    category: "cybercrime",
  },
  {
    id: 11,
    question: "What is cyberstalking?",
    options: [
      "Using technology to harass or threaten someone repeatedly",
      "Stealing credit card information",
      "Hacking into government systems",
      "Creating computer viruses",
    ],
    correctAnswer: 0,
    category: "cybercrime",
  },
  {
    id: 12,
    question: "Which of these is a sign of a phishing email?",
    options: [
      "Professional formatting",
      "Urgent language demanding immediate action",
      "Personalized greeting",
      "Company logo",
    ],
    correctAnswer: 1,
    category: "cybercrime",
  },
  {
    id: 13,
    question: "What is the primary goal of social engineering?",
    options: [
      "To improve social media presence",
      "To manipulate people into revealing confidential information",
      "To create social networks",
      "To enhance communication skills",
    ],
    correctAnswer: 1,
    category: "cybercrime",
  },
  {
    id: 14,
    question: "Which attack intercepts communication between two parties?",
    options: ["Brute force attack", "Man-in-the-middle attack", "Dictionary attack", "Rainbow table attack"],
    correctAnswer: 1,
    category: "cybercrime",
  },
  {
    id: 15,
    question: "What is vishing?",
    options: ["Video phishing", "Voice phishing (phone-based)", "Virtual phishing", "Visual phishing"],
    correctAnswer: 1,
    category: "cybercrime",
  },
  {
    id: 16,
    question: "Which of these helps protect against malware?",
    options: [
      "Disabling firewall",
      "Opening all email attachments",
      "Keeping software updated",
      "Using public Wi-Fi for banking",
    ],
    correctAnswer: 2,
    category: "cybercrime",
  },
  {
    id: 17,
    question: "What is a keylogger?",
    options: ["A type of keyboard", "Software that records keystrokes", "A password generator", "A typing speed test"],
    correctAnswer: 1,
    category: "cybercrime",
  },
  {
    id: 18,
    question: "Which practice makes you vulnerable to cyber attacks?",
    options: [
      "Using two-factor authentication",
      "Regular software updates",
      "Using the same password for multiple accounts",
      "Installing antivirus software",
    ],
    correctAnswer: 2,
    category: "cybercrime",
  },
  {
    id: 19,
    question: "What is smishing?",
    options: ["Email phishing", "SMS/text message phishing", "Social media phishing", "Phone call phishing"],
    correctAnswer: 1,
    category: "cybercrime",
  },
  {
    id: 20,
    question: "Which of these is a characteristic of secure websites?",
    options: ["HTTP protocol", "No encryption", "HTTPS protocol with SSL certificate", "Pop-up advertisements"],
    correctAnswer: 2,
    category: "cybercrime",
  },

  // Cyber Literacy Questions
  {
    id: 21,
    question: "What does cyber literacy primarily involve?",
    options: [
      "Programming skills only",
      "Understanding how to use technology safely and effectively",
      "Gaming expertise",
      "Social media marketing",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 22,
    question: "Which skill is essential for cyber literacy?",
    options: ["Advanced coding", "Critical evaluation of online information", "Video editing", "Graphic design"],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 23,
    question: "What is digital citizenship?",
    options: [
      "Having a digital ID card",
      "Responsible and ethical use of technology",
      "Living in a smart city",
      "Working in IT industry",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 24,
    question: "Why is it important to verify information found online?",
    options: [
      "To waste time",
      "Because all online information is false",
      "To avoid spreading misinformation",
      "It's not important",
    ],
    correctAnswer: 2,
    category: "cyber-literacy",
  },
  {
    id: 25,
    question: "What should you do before sharing personal information online?",
    options: [
      "Share it immediately",
      "Check privacy settings and understand who can see it",
      "Post it on all social media platforms",
      "Send it to strangers",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 26,
    question: "What does HTTPS stand for?",
    options: [
      "HyperText Transfer Protocol Secure",
      "High Tech Transfer Protocol System",
      "HyperText Transport Protocol Safe",
      "High Transfer Text Protocol Secure",
    ],
    correctAnswer: 0,
    category: "cyber-literacy",
  },
  {
    id: 27,
    question: "What is two-factor authentication (2FA)?",
    options: [
      "Using two different passwords",
      "An additional security layer requiring two forms of identification",
      "Having two user accounts",
      "Using two different browsers",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 28,
    question: "What makes a strong password?",
    options: [
      "Using only numbers",
      "Using personal information",
      "Combination of uppercase, lowercase, numbers, and special characters",
      "Using the same password everywhere",
    ],
    correctAnswer: 2,
    category: "cyber-literacy",
  },
  {
    id: 29,
    question: "What is a VPN?",
    options: [
      "Very Private Network",
      "Virtual Private Network",
      "Verified Personal Network",
      "Visual Protection Network",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 30,
    question: "What should you do if you receive a suspicious email?",
    options: [
      "Click on all links to investigate",
      "Forward it to all your contacts",
      "Delete it and report it as spam",
      "Reply asking for more information",
    ],
    correctAnswer: 2,
    category: "cyber-literacy",
  },
  {
    id: 31,
    question: "What is the purpose of antivirus software?",
    options: [
      "To speed up your computer",
      "To detect and remove malicious software",
      "To manage your files",
      "To connect to the internet",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 32,
    question: "What is a firewall?",
    options: [
      "A physical wall around computers",
      "A security system that monitors and controls network traffic",
      "A type of virus",
      "A backup system",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 33,
    question: "What does it mean to 'encrypt' data?",
    options: [
      "To delete data permanently",
      "To convert data into a coded format to prevent unauthorized access",
      "To copy data to multiple locations",
      "To compress data to save space",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 34,
    question: "What is cloud storage?",
    options: [
      "Storage in the sky",
      "Storing data on remote servers accessed via internet",
      "Storage on your local computer",
      "Storage on physical CDs",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 35,
    question: "What should you do before downloading software from the internet?",
    options: [
      "Download from any website",
      "Verify the source and check for reviews",
      "Download multiple versions",
      "Share the download link with friends",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },

  // Online Safety Questions
  {
    id: 51,
    question: "What is the safest way to connect to the internet in public places?",
    options: [
      "Use public Wi-Fi without password",
      "Connect to any available network",
      "Use a VPN on trusted networks",
      "Share your mobile hotspot password",
    ],
    correctAnswer: 2,
    category: "online-safety",
  },
  {
    id: 52,
    question: "Which information should you never share on social media?",
    options: [
      "Your favorite movie",
      "Your full address and phone number",
      "Your hobby interests",
      "Your favorite food",
    ],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 53,
    question: "What should you do if you receive a suspicious email?",
    options: [
      "Forward it to all contacts",
      "Click all links to investigate",
      "Delete it and report as spam",
      "Reply asking for more information",
    ],
    correctAnswer: 2,
    category: "online-safety",
  },
  {
    id: 54,
    question: "How often should you update your passwords?",
    options: ["Never", "Once a year", "Regularly, especially after security breaches", "Only when you forget them"],
    correctAnswer: 2,
    category: "online-safety",
  },
  {
    id: 55,
    question: "What is the best practice for online shopping?",
    options: [
      "Use public computers for purchases",
      "Save credit card info on all websites",
      "Shop only on secure, reputable websites",
      "Share your card details via email",
    ],
    correctAnswer: 2,
    category: "online-safety",
  },
  {
    id: 56,
    question: "What information should you NEVER share on social media?",
    options: ["Your favorite movies", "Your full address and phone number", "Your hobbies", "Your school name"],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 57,
    question: "What should you do if someone you don't know tries to contact you online?",
    options: [
      "Share all your personal information",
      "Meet them in person immediately",
      "Be cautious and don't share personal information",
      "Give them your home address",
    ],
    correctAnswer: 2,
    category: "online-safety",
  },
  {
    id: 58,
    question: "What is cyberbullying?",
    options: [
      "Playing online games",
      "Using digital platforms to harass, threaten, or intimidate others",
      "Learning about computers",
      "Creating social media accounts",
    ],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 59,
    question: "What should you do if you encounter cyberbullying?",
    options: [
      "Ignore it completely",
      "Fight back with more aggressive messages",
      "Report it to authorities and block the bully",
      "Share the bully's information publicly",
    ],
    correctAnswer: 2,
    category: "online-safety",
  },
  {
    id: 60,
    question: "What is the safest way to shop online?",
    options: [
      "Use public Wi-Fi for transactions",
      "Share your credit card details via email",
      "Use secure websites (HTTPS) and trusted payment methods",
      "Save payment information on every website",
    ],
    correctAnswer: 2,
    category: "online-safety",
  },
  {
    id: 61,
    question: "What should you check before entering personal information on a website?",
    options: [
      "The website's color scheme",
      "The website's URL and security certificates",
      "The number of images on the page",
      "The website's loading speed",
    ],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 62,
    question: "What is the risk of using public Wi-Fi for sensitive activities?",
    options: [
      "Slower internet speed",
      "Higher data usage",
      "Potential interception of personal data",
      "Limited website access",
    ],
    correctAnswer: 2,
    category: "online-safety",
  },
  {
    id: 63,
    question: "What should you do with your privacy settings on social media?",
    options: [
      "Keep everything public",
      "Review and adjust them regularly for maximum privacy",
      "Never change them",
      "Let others manage them",
    ],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 64,
    question: "What is 'oversharing' on social media?",
    options: [
      "Sharing too many photos",
      "Sharing excessive personal information that could be misused",
      "Sharing other people's posts",
      "Sharing educational content",
    ],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 65,
    question: "What should you do if you accidentally click on a suspicious link?",
    options: [
      "Continue browsing normally",
      "Immediately close the browser and run antivirus scan",
      "Share the link with friends",
      "Download any suggested software",
    ],
    correctAnswer: 1,
    category: "online-safety",
  },

  // Digital Security Questions
  {
    id: 76,
    question: "What is two-factor authentication (2FA)?",
    options: [
      "Using two passwords",
      "An additional security layer requiring a second form of verification",
      "Having two user accounts",
      "Using two different browsers",
    ],
    correctAnswer: 1,
    category: "digital-security",
  },
  {
    id: 77,
    question: "Which of these is the most secure way to store passwords?",
    options: [
      "Writing them on paper",
      "Saving in browser without master password",
      "Using a reputable password manager",
      "Using the same password everywhere",
    ],
    correctAnswer: 2,
    category: "digital-security",
  },
  {
    id: 78,
    question: "What does end-to-end encryption mean?",
    options: [
      "Data is encrypted only at the sender's end",
      "Data is encrypted during transmission and can only be decrypted by intended recipient",
      "Data is never encrypted",
      "Data is encrypted only at the receiver's end",
    ],
    correctAnswer: 1,
    category: "digital-security",
  },
  {
    id: 79,
    question: "Why should you log out of accounts on shared computers?",
    options: [
      "To save electricity",
      "To prevent unauthorized access to your accounts",
      "It's not necessary",
      "To free up memory",
    ],
    correctAnswer: 1,
    category: "digital-security",
  },
  {
    id: 80,
    question: "What is a firewall's primary function?",
    options: [
      "To speed up internet connection",
      "To monitor and control incoming and outgoing network traffic",
      "To store passwords",
      "To clean temporary files",
    ],
    correctAnswer: 1,
    category: "digital-security",
  },
  {
    id: 81,
    question: "What should you do if your account gets hacked?",
    options: [
      "Ignore it",
      "Change passwords immediately and enable 2FA",
      "Create a new account with same password",
      "Wait for it to fix itself",
    ],
    correctAnswer: 1,
    category: "digital-security",
  },
  {
    id: 82,
    question: "Which of these is a sign of a secure password?",
    options: [
      "Contains personal information",
      "Is short and simple",
      "Is long and contains mixed characters",
      "Is the same as username",
    ],
    correctAnswer: 2,
    category: "digital-security",
  },
  {
    id: 83,
    question: "What is the purpose of software updates?",
    options: [
      "To make software slower",
      "To fix security vulnerabilities and bugs",
      "To use more storage space",
      "To change the interface only",
    ],
    correctAnswer: 1,
    category: "digital-security",
  },
  {
    id: 36,
    question: "How often should you update your software?",
    options: ["Never", "Once a year", "Regularly when updates are available", "Only when the computer stops working"],
    correctAnswer: 2,
    category: "digital-security",
  },
  {
    id: 37,
    question: "What is the purpose of software updates?",
    options: [
      "To make software slower",
      "To fix security vulnerabilities and bugs",
      "To use more storage space",
      "To change the software's appearance",
    ],
    correctAnswer: 1,
    category: "digital-security",
  },
  {
    id: 38,
    question: "What is a security patch?",
    options: [
      "A physical repair to computer hardware",
      "A software update that fixes security vulnerabilities",
      "A type of antivirus software",
      "A backup system",
    ],
    correctAnswer: 1,
    category: "digital-security",
  },
  {
    id: 39,
    question: "What should you do with suspicious email attachments?",
    options: [
      "Open them immediately",
      "Don't open them and scan with antivirus if necessary",
      "Forward them to friends",
      "Save them for later",
    ],
    correctAnswer: 1,
    category: "digital-security",
  },
  {
    id: 40,
    question: "What is the best practice for password management?",
    options: [
      "Use the same password for everything",
      "Write passwords on sticky notes",
      "Use a password manager with unique passwords",
      "Share passwords with trusted friends",
    ],
    correctAnswer: 2,
    category: "digital-security",
  },
  {
    id: 41,
    question: "What is biometric authentication?",
    options: [
      "Using biological characteristics like fingerprints for identification",
      "A type of password",
      "A security software",
      "A type of encryption",
    ],
    correctAnswer: 0,
    category: "digital-security",
  },
  {
    id: 42,
    question: "What should you do before disposing of an old computer?",
    options: [
      "Just throw it away",
      "Sell it immediately",
      "Securely wipe all data from the hard drive",
      "Give it to anyone who wants it",
    ],
    correctAnswer: 2,
    category: "digital-security",
  },
  {
    id: 43,
    question: "What is end-to-end encryption?",
    options: [
      "Encryption that works only at the beginning",
      "Encryption that protects data throughout its entire journey",
      "Encryption that stops working at the end",
      "A type of password protection",
    ],
    correctAnswer: 1,
    category: "digital-security",
  },
  {
    id: 44,
    question: "What is a digital certificate?",
    options: [
      "An online diploma",
      "An electronic document that proves the identity of a website or organization",
      "A type of software license",
      "A computer warranty",
    ],
    correctAnswer: 1,
    category: "digital-security",
  },
  {
    id: 45,
    question: "What should you do if you suspect your account has been compromised?",
    options: [
      "Continue using it normally",
      "Immediately change passwords and enable 2FA",
      "Delete the account",
      "Share the account with others",
    ],
    correctAnswer: 1,
    category: "digital-security",
  },

  // Additional Cybercrime Questions
  {
    id: 46,
    question: "What is cryptocurrency fraud?",
    options: [
      "Legal cryptocurrency trading",
      "Scams involving fake cryptocurrency investments or theft",
      "Mining cryptocurrency",
      "Using cryptocurrency for purchases",
    ],
    correctAnswer: 1,
    category: "cybercrime",
  },
  {
    id: 47,
    question: "What is online auction fraud?",
    options: [
      "Legitimate online bidding",
      "Fraudulent schemes in online auction sites",
      "Selling items online",
      "Buying items from auctions",
    ],
    correctAnswer: 1,
    category: "cybercrime",
  },
  {
    id: 48,
    question: "What is romance scam?",
    options: [
      "Online dating",
      "Fraudulent scheme where criminals create fake romantic relationships to steal money",
      "Social media friendship",
      "Video calling with friends",
    ],
    correctAnswer: 1,
    category: "cybercrime",
  },
  {
    id: 49,
    question: "What is tech support scam?",
    options: [
      "Legitimate technical help",
      "Fraudulent calls claiming to fix computer problems for money",
      "Software installation service",
      "Computer repair shop",
    ],
    correctAnswer: 1,
    category: "cybercrime",
  },
  {
    id: 50,
    question: "What is email spoofing?",
    options: [
      "Sending legitimate emails",
      "Forging email headers to make emails appear from trusted sources",
      "Creating email accounts",
      "Organizing email folders",
    ],
    correctAnswer: 1,
    category: "cybercrime",
  },
  {
    id: 51,
    question: "What is a keylogger?",
    options: [
      "A type of keyboard",
      "Malicious software that records keystrokes",
      "A password manager",
      "A typing tutorial program",
    ],
    correctAnswer: 1,
    category: "cybercrime",
  },
  {
    id: 52,
    question: "What is credit card skimming?",
    options: [
      "Reading credit card statements",
      "Illegally copying credit card information using hidden devices",
      "Applying for credit cards",
      "Paying with credit cards",
    ],
    correctAnswer: 1,
    category: "cybercrime",
  },
  {
    id: 53,
    question: "What is pharming?",
    options: [
      "Agricultural website",
      "Redirecting users from legitimate websites to fraudulent ones",
      "Online shopping",
      "Social media farming",
    ],
    correctAnswer: 1,
    category: "cybercrime",
  },
  {
    id: 54,
    question: "What is a man-in-the-middle attack?",
    options: [
      "Physical assault",
      "Intercepting communication between two parties",
      "Group conversation",
      "Video conference",
    ],
    correctAnswer: 1,
    category: "cybercrime",
  },
  {
    id: 55,
    question: "What is cyber extortion?",
    options: [
      "Legal business practice",
      "Threatening to harm someone's digital assets unless payment is made",
      "Online fundraising",
      "Digital marketing",
    ],
    correctAnswer: 1,
    category: "cybercrime",
  },

  // Additional Cyber Literacy Questions
  {
    id: 56,
    question: "What is digital footprint?",
    options: [
      "Physical footprints on devices",
      "Trail of data you leave when using the internet",
      "Computer hardware specifications",
      "Internet connection speed",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 57,
    question: "What is metadata?",
    options: [
      "Large amounts of data",
      "Data that provides information about other data",
      "Deleted data",
      "Encrypted data",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 58,
    question: "What is the purpose of cookies on websites?",
    options: [
      "To slow down websites",
      "To store user preferences and track browsing behavior",
      "To display advertisements only",
      "To protect against viruses",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 59,
    question: "What is digital literacy?",
    options: [
      "Ability to read digital clocks",
      "Skills needed to find, evaluate, and communicate information using digital technologies",
      "Knowledge of computer hardware",
      "Ability to type fast",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 60,
    question: "What is the difference between HTTP and HTTPS?",
    options: [
      "No difference",
      "HTTPS is the secure version with encryption",
      "HTTP is newer than HTTPS",
      "HTTPS is only for mobile devices",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 61,
    question: "What is a browser cache?",
    options: [
      "Browser's memory storage",
      "Temporary storage of web page data to speed up loading",
      "Browser's security system",
      "Browser's bookmark system",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 62,
    question: "What is the purpose of incognito/private browsing mode?",
    options: [
      "To browse faster",
      "To browse without saving history, cookies, or site data locally",
      "To access blocked websites",
      "To use less internet data",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 63,
    question: "What is a URL?",
    options: [
      "User Registration Link",
      "Uniform Resource Locator - web address",
      "Universal Reading Language",
      "User Requirement List",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 64,
    question: "What is bandwidth?",
    options: [
      "Width of computer screen",
      "Amount of data that can be transmitted over internet connection",
      "Size of computer memory",
      "Number of websites you can visit",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 65,
    question: "What is the cloud?",
    options: [
      "Weather phenomenon",
      "Network of remote servers for storing and accessing data over internet",
      "Type of computer virus",
      "Social media platform",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },

  // Additional Online Safety Questions
  {
    id: 66,
    question: "What should you do if you receive a friend request from someone you don't know?",
    options: [
      "Accept immediately",
      "Ignore or decline the request",
      "Share your personal information",
      "Meet them in person",
    ],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 67,
    question: "What is sexting and why is it risky?",
    options: [
      "Safe online communication",
      "Sending sexually explicit messages/images, risky due to potential misuse",
      "Educational content sharing",
      "Professional networking",
    ],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 68,
    question: "What should you do if someone asks for your password?",
    options: [
      "Share it immediately",
      "Never share passwords with anyone",
      "Share only with close friends",
      "Write it down for them",
    ],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 69,
    question: "What is grooming in online context?",
    options: [
      "Personal hygiene tips",
      "Process where predators build trust to exploit minors",
      "Professional development",
      "Social media management",
    ],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 70,
    question: "What information is safe to share in online gaming?",
    options: ["Real name and address", "Gaming username only", "School and personal details", "Family information"],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 71,
    question: "What should you do if you see inappropriate content online?",
    options: ["Share it with friends", "Report it to appropriate authorities", "Download and save it", "Comment on it"],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 72,
    question: "What is digital citizenship?",
    options: [
      "Having a digital ID card",
      "Responsible and ethical use of technology",
      "Living in a digital city",
      "Working in tech industry",
    ],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 73,
    question: "What should you do before posting a photo online?",
    options: [
      "Post immediately",
      "Consider privacy implications and who can see it",
      "Add as many tags as possible",
      "Share location details",
    ],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 74,
    question: "What is the risk of geo-tagging photos?",
    options: [
      "Better photo quality",
      "Revealing your location to potential stalkers",
      "Faster upload speed",
      "More likes on social media",
    ],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 75,
    question: "What should you do if you encounter hate speech online?",
    options: [
      "Respond with more hate speech",
      "Report it and don't engage",
      "Share it with others",
      "Ignore it completely",
    ],
    correctAnswer: 1,
    category: "online-safety",
  },

  // Additional Digital Security Questions
  {
    id: 84,
    question: "Which practice helps protect your privacy online?",
    options: [
      "Accepting all cookies",
      "Sharing location with all apps",
      "Reviewing and adjusting privacy settings regularly",
      "Using public Wi-Fi for sensitive tasks",
    ],
    correctAnswer: 2,
    category: "online-safety",
  },
  {
    id: 85,
    question: "What is cyberbullying?",
    options: [
      "Using technology to harass, threaten, or humiliate others",
      "Playing online games",
      "Learning about computers",
      "Using social media",
    ],
    correctAnswer: 0,
    category: "online-safety",
  },
  {
    id: 86,
    question: "How can you identify fake news online?",
    options: [
      "Believe everything you read",
      "Check multiple reliable sources and verify facts",
      "Share immediately",
      "Only read headlines",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 87,
    question: "What is the dark web?",
    options: [
      "A website with dark colors",
      "Part of the internet that requires special software to access",
      "A social media platform",
      "A type of malware",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 88,
    question: "Which of these is a safe browsing practice?",
    options: [
      "Clicking on all pop-up ads",
      "Downloading software from unknown sources",
      "Verifying website URLs before entering sensitive information",
      "Disabling security warnings",
    ],
    correctAnswer: 2,
    category: "online-safety",
  },
  {
    id: 89,
    question: "What is cryptocurrency mining malware?",
    options: [
      "Software that helps you mine legally",
      "Malware that uses your computer to mine cryptocurrency without permission",
      "A type of antivirus",
      "A legitimate mining tool",
    ],
    correctAnswer: 1,
    category: "cybercrime",
  },
  {
    id: 90,
    question: "How should you handle suspicious phone calls asking for personal information?",
    options: [
      "Provide all requested information",
      "Hang up and verify the caller's identity independently",
      "Give partial information",
      "Ask them to call back later",
    ],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 91,
    question: "What is the purpose of HTTPS?",
    options: [
      "To make websites load faster",
      "To provide secure, encrypted communication between browser and server",
      "To display better graphics",
      "To reduce data usage",
    ],
    correctAnswer: 1,
    category: "digital-security",
  },
  {
    id: 92,
    question: "Which of these is a characteristic of a phishing website?",
    options: [
      "Professional design",
      "Secure HTTPS connection",
      "Suspicious URL that mimics legitimate sites",
      "Fast loading speed",
    ],
    correctAnswer: 2,
    category: "cybercrime",
  },
  {
    id: 93,
    question: "What should you do before downloading apps?",
    options: [
      "Download from any website",
      "Check reviews, permissions, and download from official stores",
      "Install immediately without reading",
      "Share the app with friends first",
    ],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 94,
    question: "What is digital footprint?",
    options: [
      "The size of your computer files",
      "The trail of data you leave behind when using the internet",
      "Your typing speed",
      "The number of devices you own",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 95,
    question: "How can you protect yourself from online scams?",
    options: [
      "Trust all online offers",
      "Be skeptical of too-good-to-be-true offers and verify before acting",
      "Share personal information freely",
      "Click on all advertisements",
    ],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 96,
    question: "What is the importance of backing up data?",
    options: [
      "It's not important",
      "To protect against data loss from hardware failure or cyber attacks",
      "To use more storage space",
      "To slow down your computer",
    ],
    correctAnswer: 1,
    category: "digital-security",
  },
  {
    id: 97,
    question: "Which of these is a safe way to use public Wi-Fi?",
    options: [
      "Access banking websites directly",
      "Avoid accessing sensitive information or use VPN",
      "Share the password with everyone",
      "Turn off all security settings",
    ],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 98,
    question: "What is the role of antivirus software?",
    options: [
      "To speed up computer",
      "To detect, prevent, and remove malicious software",
      "To manage files",
      "To improve graphics",
    ],
    correctAnswer: 1,
    category: "digital-security",
  },
  {
    id: 99,
    question: "How should you respond to cyberbullying?",
    options: [
      "Ignore it completely",
      "Respond aggressively",
      "Document evidence, block the bully, and report to authorities",
      "Share it with everyone",
    ],
    correctAnswer: 2,
    category: "online-safety",
  },
  {
    id: 100,
    question: "What is the best approach to CyberVaani?",
    options: [
      "Rely only on antivirus software",
      "Use a layered approach with multiple security measures",
      "Avoid using technology",
      "Trust all websites and emails",
    ],
    correctAnswer: 1,
    category: "digital-security",
  },
]

// Function to get random questions for quiz
export function getRandomQuestions(count = 10): QuizQuestion[] {
  const shuffled = [...quizQuestions].sort(() => 0.5 - Math.random())
  return shuffled.slice(0, count)
}

// Function to get questions by category
export function getQuestionsByCategory(category: QuizQuestion["category"]): QuizQuestion[] {
  return quizQuestions.filter((q) => q.category === category)
}
