export interface QuizQuestion {
  id: number
  question: string
  options: string[]
  correctAnswer: number // index of correct option (0-3)
  category: "cybercrime" | "cyber-literacy" | "online-safety" | "digital-security"
}

export const quizQuestions: QuizQuestion[] = [
  // Cybercrime Questions
  {
    id: 1,
    question: "What is phishing?",
    options: [
      "A type of computer virus",
      "A method of data encryption",
      "Fraudulent attempt to obtain sensitive information by disguising as trustworthy entity",
      "A type of firewall",
    ],
    correctAnswer: 2,
    category: "cybercrime",
  },
  {
    id: 2,
    question: "Which of the following is NOT a type of malware?",
    options: [
      "Spyware",
      "Firewall",
      "Ransomware",
      "Trojan Horse",
    ],
    correctAnswer: 1,
    category: "cybercrime",
  },
  {
    id: 3,
    question: "What does ransomware typically do?",
    options: [
      "Deletes system files",
      "Monitors user activity",
      "Encrypts files and demands payment for decryption",
      "Creates fake websites",
    ],
    correctAnswer: 2,
    category: "cybercrime",
  },
  {
    id: 4,
    question: "Which of these is a common social engineering attack?",
    options: [
      "DDoS attack",
      "Pretexting",
      "Buffer overflow",
      "SQL injection",
    ],
    correctAnswer: 1,
    category: "cybercrime",
  },
  {
    id: 5,
    question: "What is identity theft?",
    options: [
      "Using someone's personal information without permission for fraudulent purposes",
      "Creating fake social media profiles",
      "Hacking into databases",
      "Stealing physical documents",
    ],
    correctAnswer: 0,
    category: "cybercrime",
  },
  {
    id: 6,
    question: "Which attack involves overwhelming a server with traffic?",
    options: [
      "Phishing",
      "DDoS (Distributed Denial of Service)",
      "Man-in-the-middle",
      "Cross-site scripting",
    ],
    correctAnswer: 1,
    category: "cybercrime",
  },
  {
    id: 7,
    question: "What is a botnet?",
    options: [
      "A password manager",
      "A secure network protocol",
      "A type of antivirus software",
      "A network of infected computers controlled remotely",
    ],
    correctAnswer: 3,
    category: "cybercrime",
  },
  {
    id: 8,
    question: "Which of these is characteristic of a strong password?",
    options: [
      "Contains a mix of uppercase, lowercase, numbers, and symbols",
      "Is easy to remember",
      "Is the same across all accounts",
      "Contains only letters",
    ],
    correctAnswer: 0,
    category: "cybercrime",
  },
  {
    id: 9,
    question: "What is spyware designed to do?",
    options: [
      "Monitor and collect user information without consent",
      "Block internet access",
      "Encrypt files",
      "Speed up computer performance",
    ],
    correctAnswer: 0,
    category: "cybercrime",
  },
  {
    id: 10,
    question: "Which method is commonly used to distribute malware?",
    options: [
      "Software updates",
      "Antivirus scans",
      "Email attachments",
      "System backups",
    ],
    correctAnswer: 2,
    category: "cybercrime",
  },
  {
    id: 11,
    question: "What is cyberstalking?",
    options: [
      "Using technology to harass or threaten someone repeatedly",
      "Hacking into government systems",
      "Stealing credit card information",
      "Creating computer viruses",
    ],
    correctAnswer: 0,
    category: "cybercrime",
  },
  {
    id: 12,
    question: "Which of these is a sign of a phishing email?",
    options: [
      "Professional formatting",
      "Personalized greeting",
      "Company logo",
      "Urgent language demanding immediate action",
    ],
    correctAnswer: 3,
    category: "cybercrime",
  },
  {
    id: 13,
    question: "What is the primary goal of social engineering?",
    options: [
      "To manipulate people into revealing confidential information",
      "To improve social media presence",
      "To create social networks",
      "To enhance communication skills",
    ],
    correctAnswer: 0,
    category: "cybercrime",
  },
  {
    id: 14,
    question: "Which attack intercepts communication between two parties?",
    options: [
      "Dictionary attack",
      "Rainbow table attack",
      "Man-in-the-middle attack",
      "Brute force attack",
    ],
    correctAnswer: 2,
    category: "cybercrime",
  },
  {
    id: 15,
    question: "What is vishing?",
    options: [
      "Video phishing",
      "Visual phishing",
      "Virtual phishing",
      "Voice phishing (phone-based)",
    ],
    correctAnswer: 3,
    category: "cybercrime",
  },
  {
    id: 16,
    question: "Which of these helps protect against malware?",
    options: [
      "Using public Wi-Fi for banking",
      "Opening all email attachments",
      "Disabling firewall",
      "Keeping software updated",
    ],
    correctAnswer: 3,
    category: "cybercrime",
  },
  {
    id: 17,
    question: "What is a keylogger?",
    options: [
      "A typing speed test",
      "A password generator",
      "Software that records keystrokes",
      "A type of keyboard",
    ],
    correctAnswer: 2,
    category: "cybercrime",
  },
  {
    id: 18,
    question: "Which practice makes you vulnerable to cyber attacks?",
    options: [
      "Using the same password for multiple accounts",
      "Using two-factor authentication",
      "Installing antivirus software",
      "Regular software updates",
    ],
    correctAnswer: 0,
    category: "cybercrime",
  },
  {
    id: 19,
    question: "What is smishing?",
    options: [
      "SMS/text message phishing",
      "Social media phishing",
      "Phone call phishing",
      "Email phishing",
    ],
    correctAnswer: 0,
    category: "cybercrime",
  },
  {
    id: 20,
    question: "Which of these is a characteristic of secure websites?",
    options: [
      "HTTPS protocol with SSL certificate",
      "No encryption",
      "Pop-up advertisements",
      "HTTP protocol",
    ],
    correctAnswer: 0,
    category: "cybercrime",
  },

  // Cyber Literacy Questions
  {
    id: 21,
    question: "What does cyber literacy primarily involve?",
    options: [
      "Understanding how to use technology safely and effectively",
      "Social media marketing",
      "Gaming expertise",
      "Programming skills only",
    ],
    correctAnswer: 0,
    category: "cyber-literacy",
  },
  {
    id: 22,
    question: "Which skill is essential for cyber literacy?",
    options: [
      "Critical evaluation of online information",
      "Video editing",
      "Advanced coding",
      "Graphic design",
    ],
    correctAnswer: 0,
    category: "cyber-literacy",
  },
  {
    id: 23,
    question: "What is digital citizenship?",
    options: [
      "Having a digital ID card",
      "Responsible and ethical use of technology",
      "Working in IT industry",
      "Living in a smart city",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 24,
    question: "Why is it important to verify information found online?",
    options: [
      "To avoid spreading misinformation",
      "Because all online information is false",
      "To waste time",
      "It's not important",
    ],
    correctAnswer: 0,
    category: "cyber-literacy",
  },
  {
    id: 25,
    question: "What should you do before sharing personal information online?",
    options: [
      "Check privacy settings and understand who can see it",
      "Post it on all social media platforms",
      "Send it to strangers",
      "Share it immediately",
    ],
    correctAnswer: 0,
    category: "cyber-literacy",
  },
  {
    id: 26,
    question: "What does HTTPS stand for?",
    options: [
      "High Tech Transfer Protocol System",
      "High Transfer Text Protocol Secure",
      "HyperText Transport Protocol Safe",
      "HyperText Transfer Protocol Secure",
    ],
    correctAnswer: 3,
    category: "cyber-literacy",
  },
  {
    id: 27,
    question: "What is two-factor authentication (2FA)?",
    options: [
      "Using two different passwords",
      "An additional security layer requiring two forms of identification",
      "Using two different browsers",
      "Having two user accounts",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 28,
    question: "What makes a strong password?",
    options: [
      "Using personal information",
      "Using only numbers",
      "Combination of uppercase, lowercase, numbers, and special characters",
      "Using the same password everywhere",
    ],
    correctAnswer: 2,
    category: "cyber-literacy",
  },
  {
    id: 29,
    question: "What is a VPN?",
    options: [
      "Very Private Network",
      "Virtual Private Network",
      "Verified Personal Network",
      "Visual Protection Network",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 30,
    question: "What should you do if you receive a suspicious email?",
    options: [
      "Click on all links to investigate",
      "Delete it and report it as spam",
      "Forward it to all your contacts",
      "Reply asking for more information",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 31,
    question: "What is the purpose of antivirus software?",
    options: [
      "To speed up your computer",
      "To manage your files",
      "To connect to the internet",
      "To detect and remove malicious software",
    ],
    correctAnswer: 3,
    category: "cyber-literacy",
  },
  {
    id: 32,
    question: "What is a firewall?",
    options: [
      "A type of virus",
      "A security system that monitors and controls network traffic",
      "A physical wall around computers",
      "A backup system",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 33,
    question: "What does it mean to 'encrypt' data?",
    options: [
      "To copy data to multiple locations",
      "To convert data into a coded format to prevent unauthorized access",
      "To delete data permanently",
      "To compress data to save space",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 34,
    question: "What is cloud storage?",
    options: [
      "Storage on your local computer",
      "Storage on physical CDs",
      "Storage in the sky",
      "Storing data on remote servers accessed via internet",
    ],
    correctAnswer: 3,
    category: "cyber-literacy",
  },
  {
    id: 35,
    question: "What should you do before downloading software from the internet?",
    options: [
      "Download from any website",
      "Download multiple versions",
      "Share the download link with friends",
      "Verify the source and check for reviews",
    ],
    correctAnswer: 3,
    category: "cyber-literacy",
  },

  // Online Safety Questions
  {
    id: 51,
    question: "What is the safest way to connect to the internet in public places?",
    options: [
      "Use public Wi-Fi without password",
      "Use a VPN on trusted networks",
      "Share your mobile hotspot password",
      "Connect to any available network",
    ],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 52,
    question: "Which information should you never share on social media?",
    options: [
      "Your hobby interests",
      "Your full address and phone number",
      "Your favorite food",
      "Your favorite movie",
    ],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 53,
    question: "What should you do if you receive a suspicious email?",
    options: [
      "Delete it and report as spam",
      "Reply asking for more information",
      "Click all links to investigate",
      "Forward it to all contacts",
    ],
    correctAnswer: 0,
    category: "online-safety",
  },
  {
    id: 54,
    question: "How often should you update your passwords?",
    options: [
      "Once a year",
      "Regularly, especially after security breaches",
      "Only when you forget them",
      "Never",
    ],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 55,
    question: "What is the best practice for online shopping?",
    options: [
      "Shop only on secure, reputable websites",
      "Use public computers for purchases",
      "Save credit card info on all websites",
      "Share your card details via email",
    ],
    correctAnswer: 0,
    category: "online-safety",
  },
  {
    id: 56,
    question: "What information should you NEVER share on social media?",
    options: [
      "Your favorite movies",
      "Your school name",
      "Your hobbies",
      "Your full address and phone number",
    ],
    correctAnswer: 3,
    category: "online-safety",
  },
  {
    id: 57,
    question: "What should you do if someone you don't know tries to contact you online?",
    options: [
      "Meet them in person immediately",
      "Share all your personal information",
      "Give them your home address",
      "Be cautious and don't share personal information",
    ],
    correctAnswer: 3,
    category: "online-safety",
  },
  {
    id: 58,
    question: "What is cyberbullying?",
    options: [
      "Creating social media accounts",
      "Using digital platforms to harass, threaten, or intimidate others",
      "Playing online games",
      "Learning about computers",
    ],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 59,
    question: "What should you do if you encounter cyberbullying?",
    options: [
      "Report it to authorities and block the bully",
      "Share the bully's information publicly",
      "Fight back with more aggressive messages",
      "Ignore it completely",
    ],
    correctAnswer: 0,
    category: "online-safety",
  },
  {
    id: 60,
    question: "What is the safest way to shop online?",
    options: [
      "Save payment information on every website",
      "Share your credit card details via email",
      "Use public Wi-Fi for transactions",
      "Use secure websites (HTTPS) and trusted payment methods",
    ],
    correctAnswer: 3,
    category: "online-safety",
  },
  {
    id: 61,
    question: "What should you check before entering personal information on a website?",
    options: [
      "The number of images on the page",
      "The website's loading speed",
      "The website's URL and security certificates",
      "The website's color scheme",
    ],
    correctAnswer: 2,
    category: "online-safety",
  },
  {
    id: 62,
    question: "What is the risk of using public Wi-Fi for sensitive activities?",
    options: [
      "Higher data usage",
      "Slower internet speed",
      "Limited website access",
      "Potential interception of personal data",
    ],
    correctAnswer: 3,
    category: "online-safety",
  },
  {
    id: 63,
    question: "What should you do with your privacy settings on social media?",
    options: [
      "Keep everything public",
      "Never change them",
      "Review and adjust them regularly for maximum privacy",
      "Let others manage them",
    ],
    correctAnswer: 2,
    category: "online-safety",
  },
  {
    id: 64,
    question: "What is 'oversharing' on social media?",
    options: [
      "Sharing excessive personal information that could be misused",
      "Sharing other people's posts",
      "Sharing educational content",
      "Sharing too many photos",
    ],
    correctAnswer: 0,
    category: "online-safety",
  },
  {
    id: 65,
    question: "What should you do if you accidentally click on a suspicious link?",
    options: [
      "Immediately close the browser and run antivirus scan",
      "Continue browsing normally",
      "Share the link with friends",
      "Download any suggested software",
    ],
    correctAnswer: 0,
    category: "online-safety",
  },

  // Digital Security Questions
  {
    id: 76,
    question: "What is two-factor authentication (2FA)?",
    options: [
      "Using two passwords",
      "Using two different browsers",
      "Having two user accounts",
      "An additional security layer requiring a second form of verification",
    ],
    correctAnswer: 3,
    category: "digital-security",
  },
  {
    id: 77,
    question: "Which of these is the most secure way to store passwords?",
    options: [
      "Using the same password everywhere",
      "Saving in browser without master password",
      "Using a reputable password manager",
      "Writing them on paper",
    ],
    correctAnswer: 2,
    category: "digital-security",
  },
  {
    id: 78,
    question: "What does end-to-end encryption mean?",
    options: [
      "Data is encrypted only at the sender's end",
      "Data is encrypted only at the receiver's end",
      "Data is encrypted during transmission and can only be decrypted by intended recipient",
      "Data is never encrypted",
    ],
    correctAnswer: 2,
    category: "digital-security",
  },
  {
    id: 79,
    question: "Why should you log out of accounts on shared computers?",
    options: [
      "To free up memory",
      "It's not necessary",
      "To prevent unauthorized access to your accounts",
      "To save electricity",
    ],
    correctAnswer: 2,
    category: "digital-security",
  },
  {
    id: 80,
    question: "What is a firewall's primary function?",
    options: [
      "To speed up internet connection",
      "To monitor and control incoming and outgoing network traffic",
      "To clean temporary files",
      "To store passwords",
    ],
    correctAnswer: 1,
    category: "digital-security",
  },
  {
    id: 81,
    question: "What should you do if your account gets hacked?",
    options: [
      "Change passwords immediately and enable 2FA",
      "Create a new account with same password",
      "Wait for it to fix itself",
      "Ignore it",
    ],
    correctAnswer: 0,
    category: "digital-security",
  },
  {
    id: 82,
    question: "Which of these is a sign of a secure password?",
    options: [
      "Is the same as username",
      "Is short and simple",
      "Contains personal information",
      "Is long and contains mixed characters",
    ],
    correctAnswer: 3,
    category: "digital-security",
  },
  {
    id: 83,
    question: "What is the purpose of software updates?",
    options: [
      "To change the interface only",
      "To fix security vulnerabilities and bugs",
      "To use more storage space",
      "To make software slower",
    ],
    correctAnswer: 1,
    category: "digital-security",
  },
  {
    id: 36,
    question: "How often should you update your software?",
    options: [
      "Regularly when updates are available",
      "Once a year",
      "Only when the computer stops working",
      "Never",
    ],
    correctAnswer: 0,
    category: "digital-security",
  },
  {
    id: 37,
    question: "What is the purpose of software updates?",
    options: [
      "To change the software's appearance",
      "To use more storage space",
      "To fix security vulnerabilities and bugs",
      "To make software slower",
    ],
    correctAnswer: 2,
    category: "digital-security",
  },
  {
    id: 38,
    question: "What is a security patch?",
    options: [
      "A type of antivirus software",
      "A software update that fixes security vulnerabilities",
      "A physical repair to computer hardware",
      "A backup system",
    ],
    correctAnswer: 1,
    category: "digital-security",
  },
  {
    id: 39,
    question: "What should you do with suspicious email attachments?",
    options: [
      "Forward them to friends",
      "Don't open them and scan with antivirus if necessary",
      "Open them immediately",
      "Save them for later",
    ],
    correctAnswer: 1,
    category: "digital-security",
  },
  {
    id: 40,
    question: "What is the best practice for password management?",
    options: [
      "Use the same password for everything",
      "Use a password manager with unique passwords",
      "Write passwords on sticky notes",
      "Share passwords with trusted friends",
    ],
    correctAnswer: 1,
    category: "digital-security",
  },
  {
    id: 41,
    question: "What is biometric authentication?",
    options: [
      "A type of encryption",
      "A security software",
      "Using biological characteristics like fingerprints for identification",
      "A type of password",
    ],
    correctAnswer: 2,
    category: "digital-security",
  },
  {
    id: 42,
    question: "What should you do before disposing of an old computer?",
    options: [
      "Sell it immediately",
      "Give it to anyone who wants it",
      "Securely wipe all data from the hard drive",
      "Just throw it away",
    ],
    correctAnswer: 2,
    category: "digital-security",
  },
  {
    id: 43,
    question: "What is end-to-end encryption?",
    options: [
      "Encryption that protects data throughout its entire journey",
      "Encryption that stops working at the end",
      "A type of password protection",
      "Encryption that works only at the beginning",
    ],
    correctAnswer: 0,
    category: "digital-security",
  },
  {
    id: 44,
    question: "What is a digital certificate?",
    options: [
      "An online diploma",
      "A type of software license",
      "A computer warranty",
      "An electronic document that proves the identity of a website or organization",
    ],
    correctAnswer: 3,
    category: "digital-security",
  },
  {
    id: 45,
    question: "What should you do if you suspect your account has been compromised?",
    options: [
      "Delete the account",
      "Share the account with others",
      "Continue using it normally",
      "Immediately change passwords and enable 2FA",
    ],
    correctAnswer: 3,
    category: "digital-security",
  },

  // Additional Cybercrime Questions
  {
    id: 46,
    question: "What is cryptocurrency fraud?",
    options: [
      "Scams involving fake cryptocurrency investments or theft",
      "Legal cryptocurrency trading",
      "Mining cryptocurrency",
      "Using cryptocurrency for purchases",
    ],
    correctAnswer: 0,
    category: "cybercrime",
  },
  {
    id: 47,
    question: "What is online auction fraud?",
    options: [
      "Selling items online",
      "Fraudulent schemes in online auction sites",
      "Buying items from auctions",
      "Legitimate online bidding",
    ],
    correctAnswer: 1,
    category: "cybercrime",
  },
  {
    id: 48,
    question: "What is romance scam?",
    options: [
      "Social media friendship",
      "Online dating",
      "Fraudulent scheme where criminals create fake romantic relationships to steal money",
      "Video calling with friends",
    ],
    correctAnswer: 2,
    category: "cybercrime",
  },
  {
    id: 49,
    question: "What is tech support scam?",
    options: [
      "Computer repair shop",
      "Legitimate technical help",
      "Fraudulent calls claiming to fix computer problems for money",
      "Software installation service",
    ],
    correctAnswer: 2,
    category: "cybercrime",
  },
  {
    id: 50,
    question: "What is email spoofing?",
    options: [
      "Creating email accounts",
      "Forging email headers to make emails appear from trusted sources",
      "Sending legitimate emails",
      "Organizing email folders",
    ],
    correctAnswer: 1,
    category: "cybercrime",
  },
  {
    id: 51,
    question: "What is a keylogger?",
    options: [
      "A type of keyboard",
      "A password manager",
      "Malicious software that records keystrokes",
      "A typing tutorial program",
    ],
    correctAnswer: 2,
    category: "cybercrime",
  },
  {
    id: 52,
    question: "What is credit card skimming?",
    options: [
      "Paying with credit cards",
      "Applying for credit cards",
      "Reading credit card statements",
      "Illegally copying credit card information using hidden devices",
    ],
    correctAnswer: 3,
    category: "cybercrime",
  },
  {
    id: 53,
    question: "What is pharming?",
    options: [
      "Agricultural website",
      "Social media farming",
      "Redirecting users from legitimate websites to fraudulent ones",
      "Online shopping",
    ],
    correctAnswer: 2,
    category: "cybercrime",
  },
  {
    id: 54,
    question: "What is a man-in-the-middle attack?",
    options: [
      "Video conference",
      "Physical assault",
      "Group conversation",
      "Intercepting communication between two parties",
    ],
    correctAnswer: 3,
    category: "cybercrime",
  },
  {
    id: 55,
    question: "What is cyber extortion?",
    options: [
      "Legal business practice",
      "Threatening to harm someone's digital assets unless payment is made",
      "Online fundraising",
      "Digital marketing",
    ],
    correctAnswer: 1,
    category: "cybercrime",
  },

  // Additional Cyber Literacy Questions
  {
    id: 56,
    question: "What is digital footprint?",
    options: [
      "Computer hardware specifications",
      "Trail of data you leave when using the internet",
      "Physical footprints on devices",
      "Internet connection speed",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 57,
    question: "What is metadata?",
    options: [
      "Large amounts of data",
      "Data that provides information about other data",
      "Encrypted data",
      "Deleted data",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 58,
    question: "What is the purpose of cookies on websites?",
    options: [
      "To display advertisements only",
      "To protect against viruses",
      "To store user preferences and track browsing behavior",
      "To slow down websites",
    ],
    correctAnswer: 2,
    category: "cyber-literacy",
  },
  {
    id: 59,
    question: "What is digital literacy?",
    options: [
      "Ability to read digital clocks",
      "Ability to type fast",
      "Skills needed to find, evaluate, and communicate information using digital technologies",
      "Knowledge of computer hardware",
    ],
    correctAnswer: 2,
    category: "cyber-literacy",
  },
  {
    id: 60,
    question: "What is the difference between HTTP and HTTPS?",
    options: [
      "HTTPS is the secure version with encryption",
      "HTTPS is only for mobile devices",
      "HTTP is newer than HTTPS",
      "No difference",
    ],
    correctAnswer: 0,
    category: "cyber-literacy",
  },
  {
    id: 61,
    question: "What is a browser cache?",
    options: [
      "Browser's memory storage",
      "Browser's security system",
      "Temporary storage of web page data to speed up loading",
      "Browser's bookmark system",
    ],
    correctAnswer: 2,
    category: "cyber-literacy",
  },
  {
    id: 62,
    question: "What is the purpose of incognito/private browsing mode?",
    options: [
      "To use less internet data",
      "To browse without saving history, cookies, or site data locally",
      "To access blocked websites",
      "To browse faster",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 63,
    question: "What is a URL?",
    options: [
      "User Requirement List",
      "Uniform Resource Locator - web address",
      "Universal Reading Language",
      "User Registration Link",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 64,
    question: "What is bandwidth?",
    options: [
      "Width of computer screen",
      "Amount of data that can be transmitted over internet connection",
      "Number of websites you can visit",
      "Size of computer memory",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 65,
    question: "What is the cloud?",
    options: [
      "Weather phenomenon",
      "Social media platform",
      "Network of remote servers for storing and accessing data over internet",
      "Type of computer virus",
    ],
    correctAnswer: 2,
    category: "cyber-literacy",
  },

  // Additional Online Safety Questions
  {
    id: 66,
    question: "What should you do if you receive a friend request from someone you don't know?",
    options: [
      "Ignore or decline the request",
      "Meet them in person",
      "Accept immediately",
      "Share your personal information",
    ],
    correctAnswer: 0,
    category: "online-safety",
  },
  {
    id: 67,
    question: "What is sexting and why is it risky?",
    options: [
      "Sending sexually explicit messages/images, risky due to potential misuse",
      "Educational content sharing",
      "Safe online communication",
      "Professional networking",
    ],
    correctAnswer: 0,
    category: "online-safety",
  },
  {
    id: 68,
    question: "What should you do if someone asks for your password?",
    options: [
      "Never share passwords with anyone",
      "Write it down for them",
      "Share only with close friends",
      "Share it immediately",
    ],
    correctAnswer: 0,
    category: "online-safety",
  },
  {
    id: 69,
    question: "What is grooming in online context?",
    options: [
      "Personal hygiene tips",
      "Professional development",
      "Process where predators build trust to exploit minors",
      "Social media management",
    ],
    correctAnswer: 2,
    category: "online-safety",
  },
  {
    id: 70,
    question: "What information is safe to share in online gaming?",
    options: [
      "School and personal details",
      "Family information",
      "Real name and address",
      "Gaming username only",
    ],
    correctAnswer: 3,
    category: "online-safety",
  },
  {
    id: 71,
    question: "What should you do if you see inappropriate content online?",
    options: [
      "Share it with friends",
      "Report it to appropriate authorities",
      "Comment on it",
      "Download and save it",
    ],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 72,
    question: "What is digital citizenship?",
    options: [
      "Living in a digital city",
      "Having a digital ID card",
      "Working in tech industry",
      "Responsible and ethical use of technology",
    ],
    correctAnswer: 3,
    category: "online-safety",
  },
  {
    id: 73,
    question: "What should you do before posting a photo online?",
    options: [
      "Post immediately",
      "Consider privacy implications and who can see it",
      "Share location details",
      "Add as many tags as possible",
    ],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 74,
    question: "What is the risk of geo-tagging photos?",
    options: [
      "Faster upload speed",
      "More likes on social media",
      "Better photo quality",
      "Revealing your location to potential stalkers",
    ],
    correctAnswer: 3,
    category: "online-safety",
  },
  {
    id: 75,
    question: "What should you do if you encounter hate speech online?",
    options: [
      "Respond with more hate speech",
      "Ignore it completely",
      "Share it with others",
      "Report it and don't engage",
    ],
    correctAnswer: 3,
    category: "online-safety",
  },

  // Additional Digital Security Questions
  {
    id: 84,
    question: "Which practice helps protect your privacy online?",
    options: [
      "Accepting all cookies",
      "Sharing location with all apps",
      "Using public Wi-Fi for sensitive tasks",
      "Reviewing and adjusting privacy settings regularly",
    ],
    correctAnswer: 3,
    category: "online-safety",
  },
  {
    id: 85,
    question: "What is cyberbullying?",
    options: [
      "Using technology to harass, threaten, or humiliate others",
      "Learning about computers",
      "Using social media",
      "Playing online games",
    ],
    correctAnswer: 0,
    category: "online-safety",
  },
  {
    id: 86,
    question: "How can you identify fake news online?",
    options: [
      "Only read headlines",
      "Share immediately",
      "Check multiple reliable sources and verify facts",
      "Believe everything you read",
    ],
    correctAnswer: 2,
    category: "cyber-literacy",
  },
  {
    id: 87,
    question: "What is the dark web?",
    options: [
      "Part of the internet that requires special software to access",
      "A social media platform",
      "A website with dark colors",
      "A type of malware",
    ],
    correctAnswer: 0,
    category: "cyber-literacy",
  },
  {
    id: 88,
    question: "Which of these is a safe browsing practice?",
    options: [
      "Downloading software from unknown sources",
      "Disabling security warnings",
      "Clicking on all pop-up ads",
      "Verifying website URLs before entering sensitive information",
    ],
    correctAnswer: 3,
    category: "online-safety",
  },
  {
    id: 89,
    question: "What is cryptocurrency mining malware?",
    options: [
      "Software that helps you mine legally",
      "A type of antivirus",
      "A legitimate mining tool",
      "Malware that uses your computer to mine cryptocurrency without permission",
    ],
    correctAnswer: 3,
    category: "cybercrime",
  },
  {
    id: 90,
    question: "How should you handle suspicious phone calls asking for personal information?",
    options: [
      "Provide all requested information",
      "Give partial information",
      "Ask them to call back later",
      "Hang up and verify the caller's identity independently",
    ],
    correctAnswer: 3,
    category: "online-safety",
  },
  {
    id: 91,
    question: "What is the purpose of HTTPS?",
    options: [
      "To make websites load faster",
      "To reduce data usage",
      "To provide secure, encrypted communication between browser and server",
      "To display better graphics",
    ],
    correctAnswer: 2,
    category: "digital-security",
  },
  {
    id: 92,
    question: "Which of these is a characteristic of a phishing website?",
    options: [
      "Fast loading speed",
      "Professional design",
      "Secure HTTPS connection",
      "Suspicious URL that mimics legitimate sites",
    ],
    correctAnswer: 3,
    category: "cybercrime",
  },
  {
    id: 93,
    question: "What should you do before downloading apps?",
    options: [
      "Download from any website",
      "Install immediately without reading",
      "Share the app with friends first",
      "Check reviews, permissions, and download from official stores",
    ],
    correctAnswer: 3,
    category: "online-safety",
  },
  {
    id: 94,
    question: "What is digital footprint?",
    options: [
      "Your typing speed",
      "The trail of data you leave behind when using the internet",
      "The size of your computer files",
      "The number of devices you own",
    ],
    correctAnswer: 1,
    category: "cyber-literacy",
  },
  {
    id: 95,
    question: "How can you protect yourself from online scams?",
    options: [
      "Trust all online offers",
      "Be skeptical of too-good-to-be-true offers and verify before acting",
      "Click on all advertisements",
      "Share personal information freely",
    ],
    correctAnswer: 1,
    category: "online-safety",
  },
  {
    id: 96,
    question: "What is the importance of backing up data?",
    options: [
      "To use more storage space",
      "To slow down your computer",
      "To protect against data loss from hardware failure or cyber attacks",
      "It's not important",
    ],
    correctAnswer: 2,
    category: "digital-security",
  },
  {
    id: 97,
    question: "Which of these is a safe way to use public Wi-Fi?",
    options: [
      "Turn off all security settings",
      "Share the password with everyone",
      "Avoid accessing sensitive information or use VPN",
      "Access banking websites directly",
    ],
    correctAnswer: 2,
    category: "online-safety",
  },
  {
    id: 98,
    question: "What is the role of antivirus software?",
    options: [
      "To manage files",
      "To speed up computer",
      "To detect, prevent, and remove malicious software",
      "To improve graphics",
    ],
    correctAnswer: 2,
    category: "digital-security",
  },
  {
    id: 99,
    question: "How should you respond to cyberbullying?",
    options: [
      "Respond aggressively",
      "Ignore it completely",
      "Share it with everyone",
      "Document evidence, block the bully, and report to authorities",
    ],
    correctAnswer: 3,
    category: "online-safety",
  },
  {
    id: 100,
    question: "What is the best approach to CyberVaani?",
    options: [
      "Avoid using technology",
      "Rely only on antivirus software",
      "Trust all websites and emails",
      "Use a layered approach with multiple security measures",
    ],
    correctAnswer: 3,
    category: "digital-security",
  },
]

// Function to get random questions for quiz
export function getRandomQuestions(count = 10): QuizQuestion[] {
  const shuffled = [...quizQuestions].sort(() => 0.5 - Math.random())
  return shuffled.slice(0, count)
}

// Function to get questions by category
export function getQuestionsByCategory(category: QuizQuestion["category"]): QuizQuestion[] {
  return quizQuestions.filter((q) => q.category === category)
}
